### ISSUE TITLE
can't open the oggextract.exe file

### ISSUE THREAD

**Issue by K-popPotato** [arkeet/oggextract#3]
When going to the oggextract.zip file via WinRar, everytime I try to open the exe file, it opens up, then immediately closes.  What do I have to do?

**Comment by K-popPotato** [comment]
Oh yeah, and here's the message I got last time: "1 [main] oggextract 36560 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
the public mailing list cygwin@cygwin.com
Usage: oggextract <filename> [<filename> ...]"

**Comment by arkeet** [comment]
Hi, this is a command-line program, so you would have to extract it somewhere and then use it from the command prompt.

The FAST_CWD message is probably because the exe was built with a version of cygwin that is outdated for your version of Windows, but it should be harmless.

**Comment by arkeet** [comment]
Hi, this is a command-line program, so you would have to extract it somewhere and then use it from the command prompt.

The FAST_CWD message is probably because the exe was built with a version of cygwin that is outdated for your version of Windows, but it should be harmless.
